### PR TITLE
make all plots discrete

### PR DESCRIPTION
**Pull request by zielvna**

### CODE REVIEW

**Review by p6te — APPROVED** [review]

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
I suggest lowering the "Reset range" and "Set full range" buttons.

1. Increase the distance between "Min - Current & Max - Current" and the concentration slider:
image

2. Lower the "Reset range" and "Set full range" buttons so they are at the level of the connection slider:
image

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
The interface jumps significantly with changes to init pool and init position (in the add liquidity by "concentration":
[Screencast from 18.07.2024 11:39:31.webm](https://github.com/user-attachments/assets/6f378e3b-5e2b-405f-96f2-b7f24d796592)

Compare it to dev:
[Screencast from 18.07.2024 11:47:51.webm](https://github.com/user-attachments/assets/d81781c1-7447-49c9-a81e-a695bf3c03c6)

**Comment by p6te** [comment]
1. to prevent jumping interfaces elements when change between init pool and new position. you should lower a bit 'set price range' component.  the elements on init pool and new position should be in the same places 
2. the high of rangeSelector panel is changing when switch between ' concentration' and 'range'

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
Overall, it looks much better than before. However, to achieve perfection, I would address two issues here:

1. Larger layout jumps here (in init pool):

[Screencast from 19.07.2024 15:33:04.webm](https://github.com/user-attachments/assets/b1601127-1361-459c-a981-81773ba4b8b6)

2. Micro layout jumps here (in init position):

[Screencast from 19.07.2024 15:30:07.webm](https://github.com/user-attachments/assets/11885036-6cc2-4123-95b3-5077449221f6)

**Review by wojciech-cichocki — APPROVED** [review]

**Pull request merged**
