### PR TITLE
add addresses of tokens in modal

### PR DESCRIPTION
**Pull request by p6te**
Zrzut ekranu z 2024-07-22 12-26-37

### CODE REVIEW

**Review by zielvna — APPROVED** [review]

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
There were more changes except for token addresses. Some changes were made to the font size, etc. Were these intentional? It looks a bit strange now

current:
Screenshot from 2024-07-16 16-34-41

master:
Screenshot from 2024-07-16 16-34-35

**Comment by p6te** [comment]
> There were more changes except for token addresses. Some changes were made to the font size, etc. Were these intentional? It looks a bit strange now
> 
> current: Screenshot from 2024-07-16 16-34-41
> 
> master: Screenshot from 2024-07-16 16-34-35

I have aligned changes to the figma design for whole modal
https://www.figma.com/design/LsofkIRxZQIgGo1p18raOy/App?node-id=2403-5774&m=dev
image

**Comment by zielvna** [comment]
image
i think we should make actual number from balance highlighted, because it looks the same like balance label

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
IMO there some things in this design that can be improved. Some have been improved compere to earlier, and some were better in the earlier design.

Here is a screenshot of the modal from dev:
Screenshot from 2024-07-21 00-19-56

Here is a screenshot of the current modal:
Screenshot from 2024-07-21 00-06-38 (copy)

IMO, we need to:

1. The ticker font is too bold. Maybe something in between (but the previous one was significantly better, much more readable. Now it gives a sense of clutter and a small amount of space between).
2. The token address is unreadable. I have to get closer to the monitor to read the address (it might be a matter of too low font spacing, colors, too small font size, or insufficient boldness idk).
3. Let's try to extend the space for highlighting a specific token, the hover space to the far right side. It seems to be cramped. I know it is aligned with the search and common tokens, but it's worth trying to see how it looks after extending it (like in Jupiter).

**Comment by zielvna** [comment]
image
i think it's a good idea to make input focused when token list is opened so user don't have to click it and can just enter ticker

**Review by wojciech-cichocki — APPROVED** [review]

**Pull request merged**
