### PR TITLE
refactor new position

### PR DESCRIPTION
**Pull request by zielvna**

### CODE REVIEW

**Comment by p6te** [comment]
You can remove placeholder for current price when tokens are not selected
image

**Review by wojciech-cichocki — APPROVED** [review]

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
There are 2 options:
1. Hide the "Concentration/Range" slider until a chart is selected.
2. Show the "Concentration/Range" slider before a chart is selected, but with a few improvements:

2A) In this view, the "Concentration/Range" slider should definitely be disabled. This is consistent with other "add liquidity" elements, which do not require connecting a wallet and are also disabled
image

2B) The slider should maintain the same position, whether the chart is enabled or disabled:
alignment to the left (should be same place as below).
Screenshot from 2024-07-28 00-58-10
alignment to the right:
Screenshot from 2024-07-28 00-58-15

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
What about the current price of TokenX/TokenX pairs? The current price should either not be displayed at all or always be in the format e.g. `1 AZERO per AZERO`
[Screencast from 28.07.2024 01:12:59.webm](https://github.com/user-attachments/assets/149419f7-dc3d-4310-8f9c-62feceff19ae)

**Comment by wojciech-cichocki** [comment]
> 2B) The slider should maintain the same position, whether the chart is enabled or disabled:
> alignment to the left (should be same place as below). Screenshot from 2024-07-28 00-58-10
> alignment to the right: Screenshot from 2024-07-28 00-58-15

As for that, I'm pointing out that the interface shouldn't move. For example, consider the case of clicking 'add liquidity' in the position details view. In such a case, data will start loading iteratively, and a quick jump of the slider from left to right will be clearly visible. Keeping the element in the same place will always be better, avoiding potential jumps that we might not even be aware of

**Comment by wojciech-cichocki** [comment]
> > 2B) The slider should maintain the same position, whether the chart is enabled or disabled:

video:
[Screencast from 28.07.2024 01:40:47.webm](https://github.com/user-attachments/assets/97b83d66-5a49-402d-b19d-f19712d45b6a)

**Comment by wojciech-cichocki** [comment]
> There are 2 options:
> 
> 1. Hide the "Concentration/Range" slider until a chart is selected.

All in all, the best option would be the first one

**Review by wojciech-cichocki — APPROVED** [review]

**Pull request merged**
