### PR TITLE
create format number and format balance functions

### PR DESCRIPTION
**Pull request by zielvna**

### CODE REVIEW

**Review by p6te — COMMENTED** [review]
the value should have at least 1 at the end to not round to zero. 
image

**Review by p6te — COMMENTED** [review]
MAX button disappeared from second input 
image

**Review by p6te — COMMENTED** [review]
current price shouldn't be formatted 
image

**Review by p6te — COMMENTED** [review]
still Max button for second input is not displayed 
image

**Review by p6te — APPROVED** [review]

**Review by wojciech-cichocki — APPROVED** [review]

**Pull request merged**
