### PR TITLE
add tooltips to buttons

### PR DESCRIPTION
**Pull request by zielvna**

### CODE REVIEW

**Comment by p6te** [comment]
image
maybe tooltip could be lower, more aligned to the icons

**Comment by p6te** [comment]
image
 can you add tooltips of transaction details?

**Review by p6te — APPROVED** [review]

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
"Exchange tokens" IMO is not a good name., it might suggest redirect to the token exchange tab. It's better to use 'Reverse token ratio'.

image

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
Above tooltip. It was better before IMO:
image

**Review by p6te — APPROVED** [review]

**Review by p6te — APPROVED** [review]

**Review by wojciech-cichocki — APPROVED** [review]

**Pull request merged**
