### PR TITLE
change naming

### PR DESCRIPTION
**Pull request by p6te**

### CODE REVIEW

**Comment by zielvna** [comment]
image
image
can you also remove things such as `Liquidity Positions` to `positions`, `+ Add liquidity` to `+ Add position`

**Comment by zielvna** [comment]
image
there are still liquidity position texts in few places

**Review by zielvna — APPROVED** [review]

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
Too mathematical and not user-friendly enough:
Screenshot from 2024-07-29 16-34-55

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
strange case:
image

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
Shouldn't the `Liquidity` option in menu be selected in the 'Position Details' and 'Add Liquidity' sections? Was this done intentionally?

image

**Review by wojciech-cichocki — CHANGES_REQUESTED** [review]
"Not enough token B"
image

**Comment by p6te** [comment]
> strange case: image

works correct in my case 
image

**Comment by p6te** [comment]
> strange case: image

works correct in my case 
image

**Review by zielvna — APPROVED** [review]

**Review by wojciech-cichocki — APPROVED** [review]

**Pull request merged**
